// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpzjpfmranhufienswjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwempwZm1yYW5odWZpZW5zd2pyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMTk5OTcsImV4cCI6MjA1OTc5NTk5N30.xnPAngr5l8rr_Na2_w63t9vw2ycm06ehok5HjXf0W48";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);